#!/usr/bin/env bash
# A bash script that displays listening ports:
#	That only shows listening sockets
#	That shows the PID and the name of the program to which each socket belongs

netstat -l --program
