#!/usr/bin/env bash
# whats keeping your Ubuntu container's Nginx from listening on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
