#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid
# Displays "To infinity and beyond indefinitely"
# Displays "I hate the kill command" when receiving SIGTERM
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when recieivng
# SIGQUIT or SIGTERM

terminate(){
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command" && terminate' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminate' SIGQUIT
	sleep 2
done
