#!/usr/bin/env bash
# Displays numbers 1 to 20 and uses case and prints
# "bad luck from China" for the 4th iteration
# "bad luck from Japan" for the 9th iteration
# "bad luck from italy" for the 17th iteration

index=1

while [ "$index" -le 20 ]; do
	echo "$index"
	case $index in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((index++))
done
