#!/bin/bash

# Install UFW
apt update
apt install ufw -y

# Set default UFW rules
ufw default deny incoming
ufw default allow outgoing

# Allow SSH
ufw allow 22/tcp

# Allow HTTP
ufw allow 80/tcp

# Allow HTTPS
ufw allow 443/tcp

# Enable UFW
ufw --force enable

# Display UFW status and rules
ufw status verbose

