#!/bin/bash

# Install UFW
sudo apt update
sudo apt install ufw -y

# Set default UFW rules
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH
sudo ufw allow 22/tcp

# Allow HTTP
sudo ufw allow 80/tcp

# Allow HTTPS
sudo ufw allow 443/tcp

# Enable UFW
sudo ufw --force enable

# Display UFW status and rules
sudo ufw status verbose

