#!/bin/bash

# Install UFW
apt update
apt install ufw -y

# Set default UFW rules
ufw default deny incoming
ufw default allow outgoing

# Allow SSH
ufw allow 22/tcp

# Allow HTTP
ufw allow 80/tcp

# Allow HTTPS
ufw allow 443/tcp

# Enable UFW
ufw --force enable

# Display UFW status and rules
ufw status verbose


# Redirect port 8080 to port 80
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 8080 -j REDIRECT --to-port 80

# Save the iptables rules
iptables-save > /etc/iptables/rules.v4

# Ensure iptables-persistent is installed
apt-get update
apt-get install iptables-persistent -y

# Enable the firewall rules to persist on reboot
iptables-persistent save
iptables-persistent reload

